Homework_6
AnnaKhiz/nodejs24_hw_KhizhniakAnna pull request #11
Opened 2024-02-26 21:42 UTC by AnnaKhiz

Якщо я використовую morgan та записую логи в файл

server.use(morgan(':method :url :status', { stream: accessLogStream }))

то параллельно в консоль вони не виводяться. так має бути? 
тому, для виводу в консоль, (за умовами задачі) я записую ще один рядок.
це правильно чи я тут щось зробила не так?

server.use(morgan(':method :url :status')), 

я так розумію, якщо йде логування в файл, то в консоль то вже зайве?

І у мене ще одне питання. Хотіла винести роути в окремий модуль, але заплуталась і не змогла це реалізувати. Проблема була саме в передачі об'єкту з даними, які я отримую з json файлу. Єдиний варіант який спрацював, це запис даних в global. Але це ж мабуть не вірно?

2024-02-27 06:22 UTC, evhenious commented
> для виводу в консоль, (за умовами задачі) я записую ще один рядок

Так, все правильно

2024-02-27 06:30 UTC, evhenious commented on middleware/validUserDataMiddleware.js
> +	req.body = {
Ти записуєш статичні дані в req.body, і потім їх валідуєш... чи є в цьому реальний сенс? Треба валідувати саме те, що приходить ззовні з ріквестом

2024-02-27 06:31 UTC, evhenious commented on middleware/validUserDataMiddleware.js
> +	if (!req.body.username || req.body.username === '') {
`!req.body.username` це теж саме що і `req.body.username === ''`, тому що пуста строка це також false. Достатньо тільки умови `!req.body.username`

2024-02-27 06:32 UTC, evhenious commented on middleware/validUserDataMiddleware.js
> +	if (!req.body.username || req.body.username === '') {
Те ж саме для рядка 19

2024-02-27 06:37 UTC, evhenious commented on server_express.js
> +const { validIDMiddleware, validUserDataMiddleware } = require("./middleware/index");
Якщо в нас є `index.js`, то можна реквайрити просто по назві папки, пам'ятаєш перше чи друге заняття? 

```javascript
const { validIDMiddleware, validUserDataMiddleware } = require("./middleware");
```

2024-02-27 06:41 UTC, evhenious commented on server_express.js
> +server.use('/users/2', router);
Це мабуть щось тестове залишилось, так? Ніхто звісно не заборонаяє один і той самий роутер вішати на різні базові шляхи, але що це дає?

2024-02-27 06:59 UTC, evhenious commented on server_express.js
> +	fs.promises.readFile(path.join('logs', 'users.json'), 'utf8').then(res => usersData = JSON.parse(res));
Два питання:
1. чому файл з (по суті) базою даних лежить в папці 'logs'?
2. якщо цього файла немає (я роблю у себе перший запуск, наприклад) - падає. По хорошому, тут би перевіряти чи файл є, і якщо немає - створювати

2024-02-27 07:04 UTC, evhenious commented on middleware/validUserDataMiddleware.js
> +	req.body = {
Більше того, незалежно від того що я передаю в ріквест баді, створюється ОДИН і ТОЙ САМИЙ юзер з оцими даними що ти захардкодила тут )

2024-02-27 07:07 UTC, evhenious commented on server_express.js
> +process.on('SIGINT', stopServer);
Достатньо тільки на SIGINT. Зараз в тебе файл записується двічі підряд )

2024-02-27 07:09 UTC, evhenious commented on server_express.js
> +	resp.send(req.body);
Тут би ще 201 повертати замість дефолтного 200...

2024-02-27 07:14 UTC, evhenious requested changes
Домашка зарахована, але пофікси будь ласка дещо:
- прибери хардкод на створенні нового юзера, щоб працювало саме з тими даними що приходять в ріквесті
- додай створення нового файла бази даних, якщо його ще немає - сервер не повинен падати, а максимум написати в лог що "база даних не знайдена, створюється новий файл з базою"

2024-02-28 07:50 UTC, AnnaKhiz commented on middleware/validUserDataMiddleware.js
> +	req.body = {
+

2024-02-28 07:51 UTC, AnnaKhiz commented on middleware/validUserDataMiddleware.js
> +	if (!req.body.username || req.body.username === '') {
+

2024-02-28 07:52 UTC, AnnaKhiz commented on server_express.js
> +const { validIDMiddleware, validUserDataMiddleware } = require("./middleware/index");
+

2024-02-28 07:52 UTC, AnnaKhiz commented on server_express.js
> +server.use('/users/2', router);
+

2024-02-28 10:52 UTC, AnnaKhiz commented on server_express.js
> +	fs.promises.readFile(path.join('logs', 'users.json'), 'utf8').then(res => usersData = JSON.parse(res));
я додала перевірку, але, коли папки не існує, при першій перевірці видає помилку (папки немає) і далі створює папку і все працює. тобто ця помилка не впливає на роботу коду.
якщо я додаю перевірку на існування папки перед тим як її створити, то запускається безкінечний цикл і скрипт запускається знову і знову. я так вважаю, що це через те, що я запускаю код через nodemon, який відстежує зміни в коді. якщо ні, підкажіть, будь-ласка де я помиляюсь.

2024-02-28 10:52 UTC, AnnaKhiz commented on server_express.js
> +process.on('SIGINT', stopServer);
+

2024-02-28 10:53 UTC, AnnaKhiz commented on server_express.js
> +	resp.send(req.body);
+

2024-02-28 10:55 UTC, evhenious commented on server_express.js
> +	fs.promises.readFile(path.join('logs', 'users.json'), 'utf8').then(res => usersData = JSON.parse(res));
Так, nodemon може це робити (реагувати на нові файли в зоні відповідальності), спробуй додати йому конфіг, в якому вкажи що деякі речі треба ігнорувати -  https://github.com/remy/nodemon?tab=readme-ov-file#config-files

2024-02-28 10:56 UTC, evhenious commented on server_express.js
> +	fs.promises.readFile(path.join('logs', 'users.json'), 'utf8').then(res => usersData = JSON.parse(res));
> але, коли папки не існує, при першій перевірці видає помилку (папки немає) і далі створює папку і все працює. тобто ця помилка не впливає на роботу коду.

запуш зміни, давай подивимось

2024-02-28 11:04 UTC, AnnaKhiz commented
дякую. виправила, але залишилось кілька питань. вище до кожного розписала.

2024-02-28 13:31 UTC, AnnaKhiz commented on server_express.js
> +	fs.promises.readFile(path.join('logs', 'users.json'), 'utf8').then(res => usersData = JSON.parse(res));
зміни запушила, нічого нового не додавала.

2024-02-28 14:57 UTC, AnnaKhiz commented
в твоєму варіанті створюється папка, у мене з цим проблем не було. синхронні варіанти я також пробувала і { recursive: true } використовувала.
а от в папці файл з базою не створюється і от при спробі це зробити виникає той незрозумілий цикл. як би я той файл не створювала.

на рахунок того, що не приходить юзер id, тут не зрозуміла. приходить весь об'єкт, який я передаю в req.body, разом з юзер айді і він же записується в "базу даних". чи я щось не про те?
![2](https://github.com/AnnaKhiz/nodejs24_hw_KhizhniakAnna/assets/105877365/24398af6-0e28-415a-a19c-d639ba6a07c2)

2024-02-28 15:07 UTC, evhenious commented
> а от в папці файл з базою не створюється

він створюється на закритті сервера, коли там потенційно є якісь дані

> разом з юзер айді і він же записується в "базу даних"

юзер айді не треба перезадвати ззовні - він має створюватись внутрішньо коли ти записуєш дані в "базу" - оцей айді і є головною ознакою того що дані в базі є. Наприклад як ми робили на заняті вчора - передаємо title + desription для муві, база його записує, призначає айді, і ми повертаємо в ріспонсі title+description+**id**

2024-02-28 15:16 UTC, AnnaKhiz commented
> він створюється на закритті сервера, коли там потенційно є якісь дані

блін, точно... а я з цим другий день сиджу.
дякую велике!

2024-02-28 15:18 UTC, evhenious commented
Замерджай цей ПР сама, будь ласка, якщо більше не будеш нічого додавати

2024-02-28 15:24 UTC, merged